Repository hapinessjs/ng-universal-module, pull requests merged in 2018-02, with the labels that each got.

#14 release(version): v5.2.5
  README.md
  package.json
  yarn.lock
Labels: dependencies, documentation

#15 feat(reply): ng-universal-module can redirect a 302 request
  package.json
  src/module/routes/universal/get/html.route.ts
  test/unit/get-html-universal.route.test.ts
  yarn.lock
Labels: dependencies, enhancement

#16 release(version): v5.3.0
  README.md
  package.json
  src/module/routes/universal/get/html.route.ts
  test/unit/get-html-universal.route.test.ts
  yarn.lock
Labels: dependencies, documentation, enhancement
